name       : python-inflection
version    : 0.3.1
release    : 2
source     :
    - https://files.pythonhosted.org/packages/d5/35/a6eb45b4e2356fe688b21570864d4aa0d0a880ce387defe9c589112077f8/inflection-0.3.1.tar.gz : 18ea7fb7a7d152853386523def08736aa8c32636b047ade55f7578c4edeb16ca
license    : MIT
component  : programming.python
summary    : A port of Ruby on Rails inflector to Python
description: |
    Inflection is a string transformation library. It singularizes and pluralizes English words, and transforms strings from CamelCase to underscored string. Inflection is a port of Ruby on Rails’ inflector to Python.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python3_setup
install    : |
    %python3_install
